export const nicknames = {

    "Atlanta": "Hawks", 
    "Boston": "Celtics",  
    "Brooklyn": "Nets", 
    "Charlotte": "Hornets",  
    "Chicago": "Bulls",  
    "Cleveland": "Cavaliers",  
    "Dallas": "Mavericks",  
    "Denver": "Nuggets",  
    "Detroit": "Pistons",  
    "Golden State": "Warriors",  
    "Houston": "Rockets",  
    "Indiana": "Pacers",  
    "LA": "Clippers",  
    "Los Angeles": "Lakers",  
    "Memphis": "Grizzlies",  
    "Miami": " Heat",  
    "Milwaukee": "Bucks",  
    "Minnesota": "Timberwolves",  
    "New Orleans": "Pelicans",  
    "New York": "Knicks",  
    "Oklahoma City": "Thunder",  
    "Orlando": "Magic",  
    "Philadelphia": "76Sixers",  
    "Phoenix": "Suns",  
    "Portland": "Trail Blazers",  
    "Sacramento": "Kings",  
    "San Antonio": "Spurs",  
    "Toronto": "Raptors",  
    "Utah": "Jazz",  
    "Washington": "Wizards"

}

export const logos = {
    "Atlanta": "Atlanta.png", 
    "Boston": "Boston.png",  
    "Brooklyn": "Brooklyn.png", 
    "Charlotte": "Charlotte.png",  
    "Chicago": "Chicago.png",  
    "Cleveland": "Cleveland.png",  
    "Dallas": "Dallas.png",  
    "Denver": "Denver.png",  
    "Detroit": "Detroit.png",  
    "Golden State": "Golden_State.png",  
    "Houston": "Houston.png",  
    "Indiana": "Indiana.png",  
    "LA": "LA.png",  
    "Los Angeles": "Los_Angeles.png",  
    "Memphis": "Memphis.png",  
    "Miami": "Miami.png",  
    "Milwaukee": "Milwaukee.png",  
    "Minnesota": "Minnesota.png",  
    "New Orleans": "New_Orleans.png",  
    "New York": "New_York.png",  
    "Oklahoma City": "Oklahoma_City.png",  
    "Orlando": "Orlando.png",  
    "Philadelphia": "Philadelphia.png",  
    "Phoenix": "Phoenix.png",  
    "Portland": "Portland.png",  
    "Sacramento": "Sacramento.png",  
    "San Antonio": "San_Antonio.png",  
    "Toronto": "Toronto.png",  
    "Utah": "Utah.png",  
    "Washington": "Washington.png"
}