export const logos = {
    "Atlanta": "Atlanta.png", 
    "Boston": "Boston.png",  
    "Brooklyn": "Brooklyn.png", 
    "Charlotte": "Charlotte.png",  
    "Chicago": "Chicago.png",  
    "Cleveland": "Cleveland.png",  
    "Dallas": "Dallas.png",  
    "Denver": "Denver.png",  
    "Detroit": "Detroit.png",  
    "Golden State": "Golden_State.png",  
    "Houston": "Houston.png",  
    "Indiana": "Indiana.png",  
    "LA": "LA.png",  
    "Los Angeles": "Los_Angeles.png",  
    "Memphis": "Memphis.png",  
    "Miami": "Miami.png",  
    "Milwaukee": "Milwaukee.png",  
    "Minnesota": "Minnesota.png",  
    "New Orleans": "New_Orleans.png",  
    "New York": "New_York.png",  
    "Oklahoma City": "Oklahoma_City.png",  
    "Orlando": "Orlando.png",  
    "Philadelphia": "Philadelphia.png",  
    "Phoenix": "Phoenix.png",  
    "Portland": "Portland.png",  
    "Sacramento": "Sacramento.png",  
    "San Antonio": "San_Antonio.png",
    "Shanghai": "Shanghai.png",  
    "Toronto": "Toronto.png",  
    "Utah": "Utah.png",  
    "Washington": "Washington.png"
}